### ISSUE TITLE
The doors facing z+in the village are installed in the opposite direction

### ISSUE THREAD

**Issue by Mobius0526** [GregTech6/gregtech6#116]
![2023-09-09_10 42 08](https://github.com/GregTech6/gregtech6/assets/62875887/85a08588-068c-4c93-8938-d3d318579568)

Doors in other directions are normal：
![2023-09-09_10 42 19](https://github.com/GregTech6/gregtech6/assets/62875887/abb233a4-babc-4217-be8c-5c77d76f2854)

**Comment by GregoriusT** [comment]
Uhm, and is that a GregTech Bug (I dont change villages apart from the bricks thing) or a Bug in some other Mod (I dont think those Mods change doors specifically) or a Bug in Vanilla? (most likely because I saw that happen in vanilla games too)

Regardless which of the three it is, I will not "fix" this issue because I am not responsible for it.
