### ISSUE TITLE
[SUGGESTION] Diesel Engine Explosions/Lubricant Consumption/Water Vapor

### ISSUE THREAD

**Issue by yuesha-yc** [GregTech6/gregtech6#30]
I suggest making the Diesel Engines more "expensive" in ways other than crafting cost because it can bring more fun and make the diesel engines a little bit more challenging to use, since they are much more convenient to use than steam turbines. 

- Make them consume Lubricant or Seed Oil or some similar fluids. 
- Disable the water generation in them because the pipes will be very disastrous if the previous suggestion is implemented. Also water generation can be comprehended as releasing the vapor directly to the atmosphere, just like gas burners did. 
- If there is no lubricant in the engines, they should stop to function and eventually lead to melt-down/explosion. 
- Don't know if pressure can be implemented as the Steam Boilers. 

Large gas motors can also have similar feature.

**Comment by GregoriusT** [comment]
Yeah, I am gonna say no to that Idea. Their Fuel Requirements are the main reason they are later in Tech, since not all Fuels can be used in them. Coal, which is basically one of the best Fuels still requires Steam to work, so a 100% switch to Diesel Engines might not be what everyone wants.

And GT6 is not really about balancing by making shit way harder to do. That is not fun.
