### ISSUE TITLE
Could you make the InvTweaks buttons a bit higher?

### ISSUE THREAD

**Issue by BoBoLittleStar** [GregTech6/gregtech6#59]
![2021-11-19_23 57 08](https://user-images.githubusercontent.com/44244431/142652784-5df3901c-38df-4d15-8a22-bcb9b01cddde.png)

**Comment by GregoriusT** [comment]
I dont actually add those Buttons myself, sooooooo, uhhhh, I do not see any Coordinates I could enter inside the Interface of InvTweaks either...

**Comment by BoBoLittleStar** [comment]
Maybe just use the GUI of big chest? Buttons for them are shown on the right when NEI is off..
BTW the AE Sky Stone Chest is also 4x9, with buttons outside the GUI so there should be a way to fix it.
![2021-11-20_05 40 04](https://user-images.githubusercontent.com/44244431/142695046-29120d10-234b-4747-a2c3-75963f01849d.png)

**Comment by GregoriusT** [comment]
The thing is it is based on where the upper boundary of the GUI is, and except for Doublechests, I made sure all my GUIs have a consistent Size, so I would need to change the Size of my GUIs in order to be able to change those Buttons.

The only thing that InvTweaks lets me decide is if its a Singlechest or a Doublechest, both of which are not good options for Button Placement.

**Comment by BoBoLittleStar** [comment]
: (
