### ISSUE TITLE
Gregtech6 on 1.12.2

### ISSUE THREAD

**Issue by hexi03** [GregTech6/gregtech6#77]
Hi, is it real to build gregtech on minecraft 1.12.2. If it is possible, I wouldn't mind, how i can do it. Thanks.
PS: I don't know much in gradle and Forge MDK, because i wouldn't mind to get some hints, how to do that.

**Comment by GregoriusT** [comment]
Does not happen, will not happen, and could never happen. There is way too much interconnected Stuff to ever port GT6 to any other MC Version.

**Comment by hexi03** [comment]
OK, thanks. But I'll try anyway

**Comment by GregoriusT** [comment]
I repeat it WILL NOT WORK, trust me, it is easier to port the entirety of future MC versions back to 1.7.10 than to port GT6 forward to to 1.8 or higher. Forge removed a LOT of features in their update to 1.8, making a lot of ways I do stuff absolutely impossible.

**Comment by hexi03** [comment]
Thanks for detailed answer. I would use 1.7.10, but Opencomputers and a lot of other mods are made for 1.12.2. 
Why has forge api changed so much? This is due to the changed Mine's codebase? Thanks again for your time.

**Comment by GregoriusT** [comment]
OpenComputers exists for 1.7.10 for sure? I think they even still release for 1.7.10 every once in a while.

And yes something changed in Minecrafts Code Base which made performance worse and dynamic custom Models near impossible, and instead of keeping the old stuff we had in 1.7.10, Forge doubled down on that bad decision by forcing Mods to use the new way.

Alone the lack of dynamically generated Block Models makes it impossible to port GT6 without rewriting literally everything. Not to mention all the Inter-Mod-Compatibility that would be lost the moment you leave 1.7.10.
