### ISSUE TITLE
Two Mininature Portals can not connect each other

### ISSUE THREAD

**Issue by mordds** [GregTech6/gregtech6#93]
Two Mininature Nether Portals can not connect each other.
they are promised in range because they are close to Vanilia portal.
both of them are Loaded by player,but they cannot found each other
Forge Version:10.13.4.1614
GregTech Version:6.15.01

**Comment by GregoriusT** [comment]
Are you sure they are "close" enough? Because Vanilla Portals can connect out of range sometimes.

**Comment by mordds** [comment]
Well,They are within range.the position are as follows
Overworld:X:-533,Z:-294
Nether:X:-66,Z:-28
And I tested it in single player world,and it works properly.
but on the server,it seems there are something wrong,because they have connected before,but after I destroy one of them and replace it at same place,it doesn't work well.

**Comment by GregoriusT** [comment]
The Coordinate Multiplier is 8 and not 10.5
Just like in vanilla, the Portals wont reliably connect if you overstretch their ranges.

**Comment by mordds** [comment]
I re-aligned the coordination of nether,now it located at X:-66 Z:-36.but something strange happened.
First,they connected each other,but I disabled the nether one by mistake.when I enable it again,only overworld one connected to the nether one,the nether one is No Target.
I just use it to transport nature gas,so it doesn't matter,but I want to know what part is wrong to avoid this next time.

More Details:
The Server is an KCauldron Server.
ChickenChunks are installed to load chunks when there is only me online.

**Comment by GregoriusT** [comment]
You have to put a Chunkloader on the Overworld one too, BOTH sides need to be chunkloaded.

**Comment by mordds** [comment]
I am very sorry to bother you again,I had done everything you said,but the problem is still exist.
the situation is just like this:
the overworld one just connected to nether one and the pipe in overworld see the pipe connected with nether one as a pipe system.
the nether one is just no target but It can receive the gas from overworld.the pipe system just contains nether pipes.
BOTH sides are chunkloaded..

**Comment by tyrael93** [comment]
MIniportals are tricky, if I do remember correctly, they actually have input and output sides both for fluids, which aren't marked and have to be found by trial and error. A good way to check is to attach a hopper to a side with some items in it and see if the item disappears. In that case, that's the item input part. Then go to the second miniportal and attach an item pipe to a chest to the opposite side you used for the input in the first one. I think top and bottom are item input/output and east/west should be fluid, but I might be wrong. Basically just check in creative mode and keep that in mind.

Or I could be completely wrong and did it wrong in my playthrough! If I do am right though, it would be a good idea to mark the input output sides in the item's tooltip, just like machines already do.

**Comment by GregoriusT** [comment]
Yeah you are indeed wrong, Mini Portals actually transfer EVERYTHING, Items, Fluids, Power etc. And it is not side specific, you just have to make sure that if you connect a Fluid Pipe to the top of one Portal,  you will have to connect a Fluid Pipe or Tank to the bottom of the second Portal, yes things that go in from the top come out the bottom, things that come in west will go out the east, etc.

You really have to be precise with where you place the Portals, because the Nether Side of the Portal has much lower tolerances than the Overworld Side (due to the 8x Factor).

And if you dont do it precisely, you end up with one Portal being able to send things to the other, but the other Portal NOT being able to send anything back. This is an intended Feature, and a consequence of how Vanilla Nether Portals inherently work.

You can have multiple Overworld Portals connecting to the same Nether Portal, but only one of the Overworld Portals (the one where the Lamp is ON) will be receiving from the Nether-Side Portal.

https://gregtech.mechaenetia.com/gallery/0-Thinking%20with%20Portals.png

**Comment by tyrael93** [comment]
>You can have multiple Overworld Portals connecting to the same Nether Portal, but only one of the Overworld Portals (the one where the Lamp is ON) will be receiving from the Nether-Side Portal.
Oh, that I didn't know. That explains why only one of my two portals was receiving.

**Comment by mordds** [comment]
I think it might be my server's problem because even I put two mini portal at x:0,z:0,they still do not connect.
At last,I am very sorry  to bother you so many times.Thank you for your answer.

**Comment by GregoriusT** [comment]
wait both are at 0;0 and still dont connect? and you manually chunkloaded both of them? maybe even using players as Chunkloaders?
